/**
 * @file safety_manager.h
 * @brief Intent + Safety Manager — evaluate confidence and apply safety gating.
 *
 * Owner: Bhagavath
 *
 * Responsibilities:
 *   - Compare EMG RMS against dynamic threshold (baseline × 2.5)
 *   - Track confidence counter (3 consecutive above-threshold windows)
 *   - Generate intent events for the Supervisor
 *   - Enforce cooldown (2.0 s) to prevent oscillatory triggers
 *   - Latch fault on sustained low-quality data
 *
 * Threshold derivation (Ju et al. 2021):
 *   - 1 s detection window, 60 ms step
 *   - Emergency braking shows sharply elevated EMG amplitude
 *   - 155.70 ms average advance time before pedal deflection
 */

#ifndef SAFETY_MANAGER_H
#define SAFETY_MANAGER_H

#include "signal_proc.h"
#include "supervisor.h"

/* ── Configuration constants ────────────────────────────────────────── */

#define SAFETY_THRESH_MULT       2.5f   /**< RMS threshold = baseline × this  */
#define SAFETY_CONFIRM_COUNT     3      /**< Consecutive above-threshold wins  */
#define SAFETY_COOLDOWN_MS       2000   /**< Cooldown after brake de-assert    */
#define SAFETY_FAULT_QUALITY_MIN 30     /**< Link quality below this → fault   */

/* ── Interface ──────────────────────────────────────────────────────── */

/** Initialise confidence counter, cooldown timer, fault latch. */
void safety_init(void);

/**
 * Evaluate the latest feature vector against safety thresholds.
 * @param features     pointer to current FeatureVector
 * @param link_quality link health from input_acq (0–100)
 */
void safety_evaluate(const FeatureVector *features, int link_quality);

/**
 * Return the most recent intent event generated by the last evaluate().
 * Returns EVT_VALID_DATA if no intent change occurred.
 */
SystemEvent safety_get_intent_event(void);

/**
 * Report a fault from an external module.
 * @param code  fault reason code (logged via output_manager)
 */
void safety_report_fault(int code);

#endif /* SAFETY_MANAGER_H */
